### ISSUE TITLE
Error on setwarp: Issue while checking leader permission

### ISSUE THREAD

**Issue by markhughes** [MarkehMe/FactionsWarps#10]
Reported by @tehrenderr at https://github.com/MarkehMe/FactionsFramework/issues/8

```
[00:07:36] [Server thread/INFO]: xXCanadianGodXx issued server command: /f setwarp GearVault SilonineOnly
[00:07:36] [Server thread/INFO]: [0;31;1m[FactionsFramework] [5m!![m[0;31;1mERROR[5m!![m[0;33;22m An internal error occured! java.lang.NullPointerException[m
[00:07:36] [Server thread/WARN]: java.lang.NullPointerException
[00:07:36] [Server thread/WARN]:    at me.markeh.factionswarps.commands.CmdWarpAdd.run(CmdWarpAdd.java:54)
[00:07:36] [Server thread/WARN]:    at me.markeh.factionsframework.command.FactionsCommand.executeWith(FactionsCommand.java:155)
[00:07:36] [Server thread/WARN]:    at me.markeh.factionsframework.layer.layer_2_7.Command_2_7.perform(Command_2_7.java:61)
[00:07:36] [Server thread/WARN]:    at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:327)
[00:07:36] [Server thread/WARN]:    at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:306)
[00:07:36] [Server thread/WARN]:    at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:349)
[00:07:36] [Server thread/WARN]:    at com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:67)
[00:07:36] [Server thread/WARN]:    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143)
[00:07:36] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[00:07:36] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
[00:07:36] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[00:07:36] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[00:07:36] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[00:07:36] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[00:07:36] [Server thread/WARN]:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[00:07:36] [Server thread/WARN]:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[00:07:36] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[00:07:36] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[00:07:36] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[00:07:36] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[00:07:36] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[00:07:36] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
[00:07:36] [Server thread/INFO]: [0;33;22mversion_info: factionsversion=Factions_2_7,frameworkversion=1.1.1,serverversion=git-PaperSpigot-"8b18730" (MC: 1.8.8)//[m
```

Source: http://pastebin.com/Hv7Cdmtj

Line 53:
https://github.com/MarkehMe/FactionsWarps/blob/5360257a97cd0eb003e0ac816d4572958d83dcdb/src/me/markeh/factionswarps/commands/CmdWarpAdd.java#L53

**Comment by DataPools** [comment]
Getting this error too. Any idea when it will be fixed?

**Comment by markhughes** [comment]
I can't replicate this yet. 

Sadly, I'm not sure why it can't get the leader of the Faction when they're offline for some. I may have to add a cache
