### ISSUE TITLE
NullPointerException when leader is offline

### ISSUE THREAD

**Issue by MedicOP** [MarkehMe/FactionsWarps#14]
/f setwarp throws NPE when leader is offline

This is because FPlayer.asBukkitPlayer returns null if the player is not online.

```java
[12-01-2017 10:15:42] [Server thread/INFO]: [FactionsFramework] !!ERROR!! An internal error occured! java.lang.NullPointerException
[12-01-2017 10:15:42] [Server thread/WARN]: java.lang.NullPointerException
[12-01-2017 10:15:42] [Server thread/WARN]: 	at me.markeh.factionswarps.commands.CmdWarpAdd.run(CmdWarpAdd.java:54)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at me.markeh.factionsframework.command.FactionsCommand.executeWith(FactionsCommand.java:155)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at me.markeh.factionsframework.layer.layer_2_8_2.Command_2_8_2.perform(Command_2_8_2.java:64)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:599)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:578)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:631)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:61)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[12-01-2017 10:15:42] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by MedicOP** [comment]
Seems to be same issue as #10

**Comment by markhughes** [comment]
Sure is. When I created this my intention was only for leaders to use it, but this will be fixed when I have some time. (very limited at the moment)
