### ISSUE TITLE
IllegalArgumentException with measuring distance to enemy

### ISSUE THREAD

**Issue by MedicOP** [MarkehMe/FactionsWarps#15]
```java
[11-01-2017 16:52:47] [Server thread/INFO]: [FactionsFramework] !!ERROR!! An internal error occured! java.lang.IllegalArgumentException: Cannot measure distance between world_nether and world
[11-01-2017 16:52:47] [Server thread/WARN]: java.lang.IllegalArgumentException: Cannot measure distance between world_nether and world
[11-01-2017 16:52:47] [Server thread/WARN]: 	at org.bukkit.Location.distanceSquared(Location.java:456)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at org.bukkit.Location.distance(Location.java:439)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at me.markeh.factionswarps.commands.CmdWarp.run(CmdWarp.java:80)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at me.markeh.factionsframework.command.FactionsCommand.executeWith(FactionsCommand.java:155)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at me.markeh.factionsframework.layer.layer_2_8_2.Command_2_8_2.perform(Command_2_8_2.java:64)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:599)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:578)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:631)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:61)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[11-01-2017 16:52:47] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[11-01-2017 16:52:47] [Server thread/INFO]: version_info: factionsversion=Factions_2_8_2,frameworkversion=1.2.0,serverversion=git-PaperSpigot-"8b18730" (MC: 1.8.8)//
```

**Comment by markhughes** [comment]
Looks like I need to add a check to see if they're in the same world first.

**Comment by markhughes** [comment]
It checks between worlds according to the code :)
