### ISSUE TITLE
i dont see whats causing this error

### ISSUE THREAD

**Issue by MarvelousStax** [MarkehMe/FactionsWarps#19]
```[16:41:10] [Server thread/INFO]: [Factions] Enabling Factions v1.6.9.5-U0.1.20
[16:41:10] [Server thread/INFO]: [Factions v1.6.9.5-U0.1.20] === ENABLE START ===
[16:41:11] [Server thread/INFO]: [Factions v1.6.9.5-U0.1.20] Loaded 6 players
[16:41:11] [Server thread/INFO]: [Factions v1.6.9.5-U0.1.20] Loaded 4 Factions
[16:41:11] [Server thread/INFO]: [Factions v1.6.9.5-U0.1.20] Loading board from disk
[16:41:11] [Server thread/INFO]: [Factions v1.6.9.5-U0.1.20] Loaded 1 board locations
[16:41:11] [Server thread/INFO]: [Factions v1.6.9.5-U0.1.20] Found playervaults hook, adding /f vault and /f setmaxvault commands.
[16:41:11] [Server thread/INFO]: [Factions v1.6.9.5-U0.1.20] Economy integration through Vault plugin successful.
[16:41:11] [Server thread/INFO]: [Factions v1.6.9.5-U0.1.20] NOTE: Economy is disabled. You can enable it with the command: f config econEnabled true
[16:41:11] [Server thread/INFO]: [Factions v1.6.9.5-U0.1.20] Successfully hooked to WorldGuard.
[16:41:11] [Server thread/INFO]: [Factions v1.6.9.5-U0.1.20] === ENABLE DONE (Took 987ms) ===
[16:41:12] [Server thread/INFO]: [FactionsTop] Enabling FactionsTop v3.3
[16:41:12] [Server thread/INFO]: [MassiveFactionsExtras] Enabling MassiveFactionsExtras v5.0
[16:41:12] [Server thread/ERROR]: [MassiveFactionsExtras] Plugin MassiveFactionsExtras v5.0 has failed to register events for class me.kowagatte.mcextras.Core because com/massivecraft/factions/entity/Faction 

[16:41:13] [Server thread/INFO]: [FactionsFramework] Enabling FactionsFramework v1.2.0
[16:41:13] [Server thread/INFO]: [0;36;1m[FactionsFramework] [0;37;1mFactions API version is: Factions_1_6[m
[16:41:13] [Server thread/INFO]: [FactionsWarps] Enabling FactionsWarps v1.1.2
[16:41:13] [Server thread/ERROR]: Error occurred while enabling FactionsWarps v1.1.2 (Is it up to date?)
java.lang.ExceptionInInitializerError
at me.markeh.factionswarps.FactionsWarps.onEnable(FactionsWarps.java:59) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [spigot.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [spigot.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [spigot.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:769) [spigot.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.Bukkit.reload(Bukkit.java:556) [spigot.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) [spigot.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) [spigot.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [spigot.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [spigot.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-PaperSpigot-"8b18730"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [spigot.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 22 column 2
at com.google.gson.Gson.fromJson(Gson.java:818) ~[spigot.jar:git-PaperSpigot-"8b18730"]
at com.google.gson.Gson.fromJson(Gson.java:768) ~[spigot.jar:git-PaperSpigot-"8b18730"]
at com.google.gson.Gson.fromJson(Gson.java:717) ~[spigot.jar:git-PaperSpigot-"8b18730"]
at com.google.gson.Gson.fromJson(Gson.java:689) ~[spigot.jar:git-PaperSpigot-"8b18730"]
at me.markeh.factionsframework.jsonconf.JSONConf.loadFrom(JSONConf.java:64) ~[?:?]
at me.markeh.factionswarps.Config.load(Config.java:90) ~[?:?]
at me.markeh.factionswarps.Config.get(Config.java:22) ~[?:?]
at me.markeh.factionswarps.commands.CmdWarp.(CmdWarp.java:40) ~[?:?]
at me.markeh.factionswarps.commands.CmdWarp.(CmdWarp.java:27) ~[?:?]
... 24 more
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 22 column 2
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[spigot.jar:git-PaperSpigot-"8b18730"]
at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:494) ~[spigot.jar:git-PaperSpigot-"8b18730"]
at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403) ~[spigot.jar:git-PaperSpigot-"8b18730"]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:166) ~[spigot.jar:git-PaperSpigot-"8b18730"]
at com.google.gson.Gson.fromJson(Gson.java:803) ~[spigot.jar:git-PaperSpigot-"8b18730"]
at com.google.gson.Gson.fromJson(Gson.java:768) ~[spigot.jar:git-PaperSpigot-"8b18730"]
at com.google.gson.Gson.fromJson(Gson.java:717) ~[spigot.jar:git-PaperSpigot-"8b18730"]
at com.google.gson.Gson.fromJson(Gson.java:689) ~[spigot.jar:git-PaperSpigot-"8b18730"]
at me.markeh.factionsframework.jsonconf.JSONConf.loadFrom(JSONConf.java:64) ~[?:?]
at me.markeh.factionswarps.Config.load(Config.java:90) ~[?:?]
at me.markeh.factionswarps.Config.get(Config.java:22) ~[?:?]
at me.markeh.factionswarps.commands.CmdWarp.(CmdWarp.java:40) ~[?:?]
at me.markeh.factionswarps.commands.CmdWarp.(CmdWarp.java:27) ~[?:?]
... 24 more
[16:41:13] [Server thread/INFO]: [FactionsWarps] Disabling FactionsWarps v1.1.2
[16:41:13] [Server thread/ERROR]: Error occurred while disabling FactionsWarps v1.1.2 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class me.markeh.factionswarps.commands.CmdWarp
at me.markeh.factionswarps.FactionsWarps.onDisable(FactionsWarps.java:88) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [spigot.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) [spigot.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [spigot.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [spigot.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [spigot.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:769) [spigot.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.Bukkit.reload(Bukkit.java:556) [spigot.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) [spigot.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) [spigot.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [spigot.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [spigot.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-PaperSpigot-"8b18730"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [spigot.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by markhughes** [comment]
```
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 22 column 2
```

This usually happens when you have manually modified a file, or it did not save correctly. 

What is the Faction ID that is associated with this?

**Comment by MarvelousStax** [comment]
How am I supposed to modify the file in game?

**Comment by markhughes** [comment]
Could you share your configuration file or something so I can try and understand your issue further? You have provided little information. It looks like a file has been modified and is not in the correct json format.

**Comment by MarvelousStax** [comment]
i fixed it but now it says i must be a officer to setwarps but im using
factions uuid which dosent go by recruit,officier ..etc

**Comment by markhughes** [comment]
There is a conversion system in place. E.g. Recruit -> member, officer -> moderator.

But FactionsUUID is dodgy and my attempts in the past to get in contact with the developer have failed. :(
