### ISSUE TITLE
Unhandled exception executing command 'f' in plugin Factions

### ISSUE THREAD

**Issue by NoHaxJustProgram** [MarkehMe/FactionsWarps#21]
[10:34:01] [Server thread/INFO]: DailyDesire issued server command: /f setwarp 1234
[10:34:01] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.1.17-b${BUILD_NUMBER}
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[server.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [server.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [server.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [server.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [server.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [server.jar:git-Spigot-550ebac-7019900]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [server.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [server.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [server.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [server.jar:git-Spigot-550ebac-7019900]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: com.massivecraft.factions.Faction.isWilderness()Z
	at me.markeh.factionsframework.layer.layer_1_6.Faction_1_6.isNone(Faction_1_6.java:176) ~[?:?]
	at me.markeh.factionsframework.command.requirements.ReqInFaction.isMet(ReqInFaction.java:33) ~[?:?]
	at me.markeh.factionsframework.command.FactionsCommand.executeWith(FactionsCommand.java:150) ~[?:?]
	at me.markeh.factionsframework.layer.layer_1_6.Command_1_6.perform(Command_1_6.java:62) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[?:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[?:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[?:?]
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:302) ~[?:?]
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:265) ~[?:?]
	at com.massivecraft.factions.P.handleCommand(P.java:180) ~[?:?]
	at com.massivecraft.factions.P.onCommand(P.java:192) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-550ebac-7019900]
	... 14 more

I just added the plugin along with factions framework and I cannot set a warp. And this is the error it gives me in the console. It says an internal error occurred while attempting to perform this command. In the mean time I will hopefully find a fix.

**Comment by markhughes** [comment]
FactionsUUID API is broken and I'm no longer supporting it.

Please consider my alternative fork, LegacyFactions:
https://www.spigotmc.org/resources/legacyfactions.40122/
