### ISSUE TITLE
NPE warps

### ISSUE THREAD

**Issue by PhanaticD** [MarkehMe/FactionsWarps#23]
I am using latest version of FactionsOne available for 1.8 https://www.spigotmc.org/resources/factionsone.9249/

```
[04:28:30 INFO]: [FactionsFramework] !!ERROR!! An internal error occured! java.lang.NullPointerException
[04:28:30 WARN]: java.lang.NullPointerException
[04:28:30 WARN]:        at me.markeh.factionswarps.commands.CmdWarpAdd.run(CmdWarpAdd.java:80)
[04:28:30 WARN]:        at me.markeh.factionsframework.command.FactionsCommand.executeWith(FactionsCommand.java:155)
[04:28:30 WARN]:        at me.markeh.factionsframework.layer.layer_1_8.Command_1_8.perform(Command_1_8.java:57)
[04:28:30 WARN]:        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:129)
[04:28:30 WARN]:        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:56)
[04:28:30 WARN]:        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:115)
[04:28:30 WARN]:        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:56)
[04:28:30 WARN]:        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:133)
[04:28:30 WARN]:        at com.massivecraft.factions.P.onCommand(P.java:193)
[04:28:30 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[04:28:30 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143)
[04:28:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[04:28:30 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194)
[04:28:30 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006)
[04:28:30 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[04:28:30 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[04:28:30 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[04:28:30 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[04:28:30 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[04:28:30 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[04:28:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[04:28:30 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[04:28:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[04:28:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[04:28:30 WARN]:        at java.lang.Thread.run(Thread.java:745)
[04:28:30 INFO]: version_info: factionsversion=Factions_1_8,frameworkversion=1.2.0,serverversion=git-TacoSpigot-"c2835df" (MC: 1.8.8)//
```

**Comment by PhanaticD** [comment]
also get this error:

```
[04:30:05] [Server thread/ERROR]: Could not pass event LandClaimEvent to FactionsFramework v1.2.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-TacoSpigot-"c2835df"]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-TacoSpigot-"c2835df"]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-TacoSpigot-"c2835df"]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [patched.jar:git-TacoSpigot-"c2835df"]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [patched.jar:git-TacoSpigot-"c2835df"]
    at com.massivecraft.factions.FPlayer.attemptClaim(FPlayer.java:640) [FactionsOne.jar:?]
    at com.massivecraft.factions.cmd.CmdClaim.perform(CmdClaim.java:41) [FactionsOne.jar:?]
    at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:129) [FactionsOne.jar:?]
    at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:56) [FactionsOne.jar:?]
    at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:115) [FactionsOne.jar:?]
    at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:56) [FactionsOne.jar:?]
    at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:133) [FactionsOne.jar:?]
    at com.massivecraft.factions.P.onCommand(P.java:193) [FactionsOne.jar:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [patched.jar:git-TacoSpigot-"c2835df"]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) [patched.jar:git-TacoSpigot-"c2835df"]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) [patched.jar:git-TacoSpigot-"c2835df"]
    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194) [patched.jar:git-TacoSpigot-"c2835df"]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006) [patched.jar:git-TacoSpigot-"c2835df"]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-TacoSpigot-"c2835df"]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-TacoSpigot-"c2835df"]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"c2835df"]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-TacoSpigot-"c2835df"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-TacoSpigot-"c2835df"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"c2835df"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"c2835df"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"c2835df"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.CraftChunk cannot be cast to java.lang.Comparable
    at java.util.TreeMap.compare(TreeMap.java:1294) ~[?:1.8.0_111]
    at java.util.TreeMap.put(TreeMap.java:538) ~[?:1.8.0_111]
    at java.util.TreeSet.add(TreeSet.java:255) ~[?:1.8.0_111]
    at me.markeh.factionsframework.layer.layer_1_8.Events_1_8.onEventFactionsChunksChange(Events_1_8.java:90) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-TacoSpigot-"c2835df"]
    ... 28 more
```
